spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

device:
  client:
    type: rest

logging:
  level:
    root: INFO
    com.example: INFO
server:
  port: 8080
