spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

machine:
  client:
    type: rest

logging:
  level:
    root: INFO
    com.example: INFO
server:
  port: 8083
  
data-service-url: ${DATA_SERVICE_URL:http://localhost:8080}
machine-service-end-point: ${MACHINE_SERVICE_END_POINT:/machines}
